#makefile 
#yooaroma : 20230104 

clean:
	rm -f ./A00_blink/obj/*.*
	rm -f ./A01_blink_key/obj/*.*
	rm -f ./A02_blink_key_irq/obj/*.*
	rm -f ./A03_blink_key_tli_irq/obj/*.*
	rm -f ./A04_blink_key_timer/obj/*.*
	rm -f ./A05_uart_irq_no/obj/*.*
	rm -f ./A11_uart_irq_rx/obj/*.*
	rm -f ./A12_uart_irq_trx/obj/*.*
	rm -f ./A13_vsprintf_test/obj/*.*
	rm -f ./A14_timer_irq/obj/*.*
	rm -f ./B01_GPIO/obj/*.*
	rm -f ./B02_AWU/obj/*.*
	rm -f ./B03_FLASH/obj/*.*
	rm -f ./B04_EEPROM/obj/*.*
	rm -f ./B05_BEEP/obj/*.*
	rm -f ./B06_IWDG/obj/*.*
	rm -f ./B07_WWDG/obj/*.*
